### PR TITLE
Handle fPIC

### PR DESCRIPTION
**Pull request by AlexandrePTJ**

### CODE REVIEW

**Comment by SSE4** [comment]
please also add the following snippet to remove fPIC for Windows:
```
    def config_options(self):
        if self.settings.os == 'Windows':
            del self.options.fPIC
```
otherwise, looks great

**Review by uilianries — APPROVED** [review]
LGTM

**Review by SSE4 — APPROVED** [review]
LGTM

**Comment by SSE4** [comment]
@uilianries CI failed for MinGW, what should we do - disable it or just ignore an error and merge?

**Comment by uilianries** [comment]
The problem is because we dont have libiconv supported on mingw. So I would say to skip libqrencode from mingw, approve this PR and open an issue to improve both packages.

@SSE4  WDYT?

**Comment by SSE4** [comment]
@uilianries agree

**Pull request merged**
